services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth_service
      - habit_tracker_service
      - user_analytics_service

  auth_service:
    build:
      context: ./auth_service
    ports:
      - "8000:8000"
    volumes:
      - ./auth_service:/src
    env_file:
      - ./auth_service/.env
    depends_on:
      - rabbitmq
  
  habit_tracker_service:
    build:
      context: ./habit_tracker_service
    ports:
      - "8001:8000"
    volumes:
      - ./habit_tracker_service:/src
    env_file:
      - ./habit_tracker_service/.env
    depends_on:
      - rabbitmq
  
  user_analytics_service:
    build:
      context: ./user_analytics_service
    ports:
      - "8002:8000"
    volumes:
      - ./user_analytics_service:/src
    env_file:
      - ./user_analytics_service/.env
    depends_on:
      - rabbitmq
  
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
